version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: brenda2802
      POSTGRES_DB: brezza
    ports:
      - "5432:5432"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: my_kafka
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: my_zookeeper
    restart: always
    ports:
      - "2181:2181"

  app:
    build: .
    container_name: my_spring_app
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/brezza
      SPRING_DATASOURCE_USERNAME: postgress
      SPRING_DATASOURCE_PASSWORD: brenda2802
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    ports:
      - "8080:8080"
